### ISSUE TITLE
"Unable to apply JMESPath query." when trying to query wp:term

### ISSUE THREAD

**Issue by jvmonjo** [elyobo/wp-rest-jmespath#3]
When I try to make a query containg a value with a colon (:) on its name, it fails.

For example: 

`_query=[*].{embedded:_embedded.wp:term.0.name}`

Is there any way to scape values like "wp:term" to avoid this?

**Comment by elyobo** [comment]
You should be able to quote the field name, e.g. `_query=[*].{embedded:_embedded."wp:term".0.name}`, although you'll need to make sure the query is correctly URL encoded to have that pass through correctly.

From the [JMESPath Spec](https://jmespath.readthedocs.io/en/latest/specification.html):

> An identifier can also be quoted. This is necessary when an identifier has characters not specified in the unquoted-string grammar rule. In this situation, an identifier is specified with a double quote, followed by any number of unescaped-char or escaped-char characters, followed by a double quote. The quoted-string rule is the same grammar rule as a JSON string, so any valid string can be used between double quoted, include JSON supported escape sequences, and six character unicode escape sequences.
